name: pomo_task
description: To-do list combained with Pomodoro.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: ^0.11.0
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^2.0.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.3
  googleapis: ^10.0.0
  intl: ^0.18.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/tomato.png

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/tomato.png"